---
output:
  html_document: default
  pdf_document: default
---
# Homework 1
**UNI:** qy2205  
**Name:** Quan Yuan  
**Email:** quan.yuan@columbia.edu  

### Part I: Importing Data into R

```{r}
# (1) import data
titanic <- read.table('Titanic.txt', as.is = TRUE, header = TRUE)

# (2) columns and rows
cat("The number of data columns is ", ncol(titanic))
cat("The number of data rows is ", nrow(titanic))

# (3) creat new variable called survived.word
survive_word <- ifelse(titanic['Survived'] == 0, 'dead', 'survived')
titanic["Survived.Word"] <- survive_word
# head(titanic, 1)
```

### Part II: Exploring the Data in R
```{r}
# (1) calculate the mean in survived, age, fare columns
apply(titanic[,c('Survived', 'Age', 'Fare')], 2, mean)
cat("The mean of survived is 0.383, which means the survival rate is very low. Only 3-4 survived among 10 people. The mean of Age is NA becasue Age column exists NA.")

# (2) Compute the proportion of female passengers who survived the titanic disaster
fsurvive <- factor(titanic[,'Survived'])
fsex <- factor(titanic[,'Sex'])
summary_2 <- summary(split(titanic[,'PassengerId'], list(fsurvive, fsex)))
cat(summary_2)
prob1 <- as.numeric(summary_2[2])/nrow(titanic)
prob1 <- round(prob1, 2)
cat("the proportion of female passengers who survived the titanic disaster is ", prob1)

# (3) Of the survivors, compute the proportion of female passengers.
prob2 <- as.numeric(summary_2[2])/(as.numeric(summary_2[2]) + as.numeric(summary_2[4]))
prob2 <- round(prob2, 2)
cat("Of the survivors, the proportion of female passengers is ", prob2)

# (4) Pclass.survival
classes <- sort(unique(titanic$Pclass))
Pclass.Survival <- vector("numeric", length = 3)
names(Pclass.Survival) <- classes
# calculate the prob
fclass = factor(titanic[,'Pclass'])
summary_class = summary(split(titanic[,'PassengerId'], list(fsurvive, fclass)))
survival_stat = summary_class[, 1]
# fill in survival rate for each class
for (i in 1:3){
  survival_each_class <- as.numeric(summary_class[, 1][paste("1.", i, sep = "")])
  nosurvival_each_class <- as.numeric(summary_class[, 1][paste("0.", i, sep = "")])
  total_number <- survival_each_class + nosurvival_each_class
  Pclass.Survival[i] <- round(survival_each_class/total_number, 2)
}
cat("the proportion of people (order: class 1, 2, 3) who survived is ", Pclass.Survival)

# (5) Pclass.survival2
Pclass.Survival2 <- round(tapply(titanic$Survived, titanic$Pclass, mean), 2)
cat("the proportion of people (order: class 1, 2, 3) who survived is (method2)", Pclass.Survival2)

# (6) Relationship between survival rate and class
cat("People in the upper class are more likely survive since the survival rate of class 1 above survive rate of class 2 and survive rate of class 2 above rate of class 3")
```



